import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/layout/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto">
          <Header />
          <div className="min-h-[600px] overflow-hidden rounded-[0.5rem] border bg-background shadow-md md:shadow-xl">
            <div className="hidden h-full flex-1 flex-col space-y-8 p-6 md:flex">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
